vim9script

filetype plugin indent on
syntax on

# PLUGINS
# catppuccin loaded from opt by colorscheme https://github.com/catppuccin/vim
packadd! vim-tene # https://github.com/kennypete/vim-tene/
set laststatus=2 # show statusline

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

# LINE NUMBERING
# Hybrid when in focus or edit, absolute in non-focus or insert. 

set number

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

# Move through soft-wrapped lines, but ignore them when moving multiple lines
# at once so that relative line numbers still make sense.
noremap <expr> j v:count ? 'j' : 'gj'
noremap <expr> k v:count ? 'k' : 'gk'

# COLORS
set termguicolors
colorscheme catppuccin_mocha
