filetype plugin indent on
syntax on

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" LINE NUMBERING
" Hybrid when in focus or edit, absolute in non-focus or insert. 

set number

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

" COLORS
set termguicolors
colorscheme catppuccin_mocha " Install plugin from https://github.com/catppuccin/vim
